services:

# https://docs.docker.com/compose/how-tos/dependent-images/#use-another-services-image-as-the-base-image

  netdisco-postgresql:
    image: localhost:5000/netdisco:${COMMITTISH:-latest}-postgresql
    build:
      context: ./netdisco-postgresql
      tags:
        - localhost:5000/netdisco:${COMMITTISH:-latest}-postgresql

  netdisco-postgresql-13:
    image: localhost:5000/netdisco:${COMMITTISH:-latest}-postgresql-13
    build:
      context: ./netdisco-postgresql
      args:
        PGVER: 13.4
      tags:
        - localhost:5000/netdisco:${COMMITTISH:-latest}-postgresql-13

  netdisco-base:
    image: localhost:5000/netdisco:${COMMITTISH:-latest}-base
    build:
      context: ./netdisco-base
      tags:
        - localhost:5000/netdisco:${COMMITTISH:-latest}-base

  netdisco-backend:
    image: localhost:5000/netdisco:${COMMITTISH:-latest}-backend
    build:
      context: ./netdisco-backend
      tags:
        - localhost:5000/netdisco:${COMMITTISH:-latest}-backend

  netdisco-web:
    image: localhost:5000/netdisco:${COMMITTISH:-latest}-web
    build:
      context: ./netdisco-web
      tags:
        - localhost:5000/netdisco:${COMMITTISH:-latest}-web
