services:

  # https://docs.docker.com/compose/how-tos/environment-variables/envvars-precedence/
  common_environment:
    image: netdisco/netdisco:latest-do
    environment:
      - NETDISCO_DOMAIN=${NETDISCO_DOMAIN:-discover}
      - NETDISCO_DB_TENANT
      - NETDISCO_DB_NAME
      - NETDISCO_DB_HOST=${NETDISCO_DB_HOST:-netdisco-postgresql}
      - NETDISCO_DB_PORT
      - NETDISCO_DB_USER
      - NETDISCO_DB_PASS
      - NETDISCO_RO_COMMUNITY
      - PGDATABASE
      - PGHOST
      - PGPORT
      - PGUSER
      - PGPASSWORD
      - NETDISCO_CURRENT_PG_VERSION=${NETDISCO_CURRENT_PG_VERSION:-18}
    profiles:
      - disabled

  netdisco-postgresql:
    image: netdisco/netdisco:latest-postgresql
    build:
      context: netdisco-postgresql
    shm_size: 128mb
    hostname: netdisco-postgresql
    volumes:
      - "./netdisco/postgresql:/var/lib/postgresql"
    extends:
      service: common_environment
    profiles: !reset null
    environment:
      - NETDISCO_DB_SUPERUSER

  netdisco-postgresql-13:
    image: netdisco/netdisco:latest-postgresql-13
    build:
      context: netdisco-postgresql
      args:
        PGVER: 13.4
    shm_size: 128mb
    hostname: netdisco-postgres-13
    volumes:
      - "./netdisco/pgdata:/var/lib/postgresql/data"
    extends:
      service: common_environment
    profiles: !reset null
    environment:
      - NETDISCO_DB_SUPERUSER

  netdisco-db-init:
    image: netdisco/netdisco:latest-do
    build:
      context: netdisco-do
    entrypoint: "/home/netdisco/bin/netdisco-env"
    command: "/home/netdisco/bin/netdisco-updatedb.sh"
    depends_on:
      netdisco-postgresql:
        condition: service_healthy
    volumes:
      - "./netdisco/pgdata:/var/lib/pgversions/pg13"
      - "./netdisco/postgresql:/var/lib/pgversions/new"
    extends:
      service: common_environment
    profiles: !reset null
    environment:
      - DEPLOY_ADMIN_USER=${DEPLOY_ADMIN_USER:-YES} # or set to NO
      - NETDISCO_ADMIN_USER
