services:

# https://docs.docker.com/compose/how-tos/dependent-images/#use-another-services-image-as-the-base-image

  netdisco-postgresql:
    build:
      context: ./netdisco-postgresql
      tags:
        - netdisco/netdisco:latest-postgresql

  netdisco-base:
    build:
      context: ./netdisco-base
      tags:
        - netdisco/netdisco:latest-base

  netdisco-backend:
    build:
      context: ./netdisco-backend
      tags:
        - netdisco/netdisco:latest-backend
      additional_contexts:
        "netdisco:latest-base": "service:netdisco-base"

  netdisco-web:
    build:
      context: ./netdisco-web
      tags:
        - netdisco/netdisco:latest-web
      additional_contexts:
        "netdisco:latest-base": "service:netdisco-base"

  netdisco-do:
    build:
      context: ./netdisco-do
      tags:
        - netdisco/netdisco:latest-do
      additional_contexts:
        "netdisco:latest-backend": "service:netdisco-backend"
