services:

  # e.g. set env NETDISCO_DB_HOST=host.docker.internal

  netdisco-postgresql:
    profiles:
      - disabled

  netdisco-postgresql-13:
    profiles:
      - disabled

  external-postgresql:
    image: netdisco/netdisco:latest-backend
    entrypoint: ''
    command: "/home/netdisco/bin/netdisco-env /usr/local/bin/pg_isready"
    environment:
      NETDISCO_DB_HOST: '${NETDISCO_DB_HOST:-}'

  netdisco-db-init:
    depends_on:
      netdisco-postgresql:
        required: false
      external-postgresql:
        condition: service_completed_successfully
