services:

# https://docs.docker.com/compose/how-tos/dependent-images/#use-another-services-image-as-the-base-image

  netdisco-postgresql:
    build:
      context: ./netdisco-postgresql
      tags:
        - netdisco/netdisco:latest-postgresql
        - localhost:5000/netdisco:latest-postgresql

  netdisco-postgresql-13:
    image: netdisco/netdisco:latest-postgresql-13
    build:
      context: ./netdisco-postgresql
      args:
        PGVER: 13.4

  netdisco-base:
    build:
      context: ./netdisco-base
      tags:
        - netdisco/netdisco:latest-base
        - localhost:5000/netdisco:latest-base

  netdisco-backend:
    build:
      context: ./netdisco-backend
      tags:
        - netdisco/netdisco:latest-backend
        - localhost:5000/netdisco:latest-backend
      additional_contexts:
        "localhost:5000/netdisco:latest-base": "service:netdisco-base"

  netdisco-web:
    build:
      context: ./netdisco-web
      tags:
        - netdisco/netdisco:latest-web
        - localhost:5000/netdisco:latest-web
      additional_contexts:
        "localhost:5000/netdisco:latest-base": "service:netdisco-base"

  netdisco-do:
    build:
      context: ./netdisco-do
      tags:
        - netdisco/netdisco:latest-do
        - localhost:5000/netdisco:latest-do
      additional_contexts:
        "localhost:5000/netdisco:latest-backend": "service:netdisco-backend"
