services:

# https://docs.docker.com/compose/how-tos/dependent-images/#use-another-services-image-as-the-base-image

  netdisco-postgresql:
    build:
      context: ./netdisco-postgresql
      tags:
        - netdisco/netdisco:${COMMITTISH}-postgresql
        - localhost:5000/netdisco:${COMMITTISH}-postgresql

  netdisco-postgresql-13:
    build:
      context: ./netdisco-postgresql
      args:
        PGVER: 13.4
      tags:
        - netdisco/netdisco:${COMMITTISH}-postgresql-13
        - localhost:5000/netdisco:${COMMITTISH}-postgresql-13

  netdisco-base:
    build:
      context: ./netdisco-base
      tags:
        - netdisco/netdisco:${COMMITTISH}-base
        - localhost:5000/netdisco:${COMMITTISH}-base

  netdisco-backend:
    build:
      context: ./netdisco-backend
      tags:
        - netdisco/netdisco:${COMMITTISH}-backend
        - localhost:5000/netdisco:${COMMITTISH}-backend
      additional_contexts:
        "localhost:5000/netdisco:${COMMITTISH}-base": "service:netdisco-base"

  netdisco-web:
    build:
      context: ./netdisco-web
      tags:
        - netdisco/netdisco:${COMMITTISH}-web
        - localhost:5000/netdisco:${COMMITTISH}-web
      additional_contexts:
        "localhost:5000/netdisco:${COMMITTISH}-base": "service:netdisco-base"
