services:

  # e.g. set env NETDISCO_DB_HOST=host.docker.internal

  netdisco-postgresql:
    profiles:
      - disabled

  external-postgresql:
    image: netdisco/netdisco:latest-do
    entrypoint: ''
    command: "/home/netdisco/bin/netdisco-env /usr/bin/pg_isready"
    environment:
      - NETDISCO_DB_HOST=${NETDISCO_DB_HOST:-}

  netdisco-do:
    depends_on: !override
      external-postgresql:
        condition: service_completed_successfully

  netdisco-db-init:
    depends_on: !override
      external-postgresql:
        condition: service_completed_successfully
