apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netdisco.fullname" . }}-config
  labels:
    {{- include "netdisco.labels" . | nindent 4 }}
data:
  deployment.yml: |
    database:
      name: '{{ .Values.db.name }}'
      user: '{{ .Values.db.user }}'
      host: '{{ include "netdisco.dbHost" . }}'
      port: {{ .Values.db.port }}

    domain_suffix: ['']
    {{- if .Values.netdisco.extraConfig }}
    {{ .Values.netdisco.extraConfig | nindent 4 }}
    {{- end }}
