apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netdisco.fullname" . }}-web
  labels:
    {{- include "netdisco.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      {{- include "netdisco.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "netdisco.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- include "netdisco.vaultAnnotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "netdisco.serviceAccountName" . }}
      securityContext:
        {{- include "netdisco.securityContext" . | nindent 8 }}
      {{- if include "netdisco.credentialsEnabled" . }}
      initContainers:
        {{- include "netdisco.initContainer" . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}-web"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.port }}
              protocol: TCP
          env:
            {{- include "netdisco.env" . | nindent 12 }}
            - name: PORT
              value: {{ .Values.web.port | quote }}
          volumeMounts:
            {{- include "netdisco.volumeMounts" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          {{- with .Values.web.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- include "netdisco.volumes" . | nindent 8 }}
