{{- if .Values.eso.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "netdisco.fullname" . }}-credentials
  labels:
    {{- include "netdisco.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.eso.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.eso.secretStoreKind }}
    name: {{ .Values.eso.secretStoreName }}
  target:
    name: {{ include "netdisco.fullname" . }}-credentials
    template:
      data:
        device_auth.yml: |
          {{- .Values.eso.deviceAuthTemplate | nindent 10 }}
  dataFrom:
    - extract:
        key: {{ .Values.eso.vaultPath }}
{{- end }}
