{{- if or .Values.route.enabled .Values.openshift }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "netdisco.fullname" . }}
  labels:
    {{- include "netdisco.labels" . | nindent 4 }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "netdisco.fullname" . }}-web
  port:
    targetPort: http
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: Redirect
  {{- end }}
{{- end }}
