{{- if not .Values.db.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netdisco.fullname" . }}-db
  labels:
    {{- include "netdisco.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.db.password | quote }}
{{- end }}
